# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input:          GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        :categories/:year/:month/:day/:title/

# Setup
title:            Tendayi Kamucheka
tagline:          'PhD Candidate @ University of Arkansas'
description:      ''
url:              https://tkamucheka.github.io
baseurl:          '/'

author:
  name:           'Tendayi Kamucheka'
  url:            https://twitter.com/tkamucheka

paginate:         3

# collections:
#   - guides

# Pages
page_excerpts: true

# Custom vars
quote:            ''

# Plugins
plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - rouge
